# Generated by Django 4.2.1 on 2023-05-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=12)),
                ('store_name', models.CharField(blank=True, max_length=70, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_code', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('outlet_type', models.CharField(max_length=9)),
                ('store_type', models.CharField(max_length=26)),
                ('store_created_date', models.DateTimeField(blank=True, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('competition_store_name', models.CharField(blank=True, max_length=70, null=True)),
                ('competition_store_uid', models.CharField(blank=True, max_length=12, null=True)),
                ('competition_store_type', models.CharField(blank=True, max_length=26, null=True)),
                ('competition_store_latitude', models.DecimalField(decimal_places=10, max_digits=18)),
                ('competition_store_longitude', models.DecimalField(decimal_places=10, max_digits=18)),
                ('competition_store_address', models.CharField(max_length=255, null=True)),
                ('competition_store_distance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('competition_store_status', models.CharField(blank=True, max_length=1, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base1.storemaster')),
            ],
            options={
                'managed': True,
                'indexes': [models.Index(fields=['store', 'year', 'week', 'competition_store_uid'], name='store_competition_idx')],
                'unique_together': {('store', 'year', 'week', 'competition_store_uid')},
            },
        ),
    ]
