# Generated by Django 4.2.1 on 2023-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecompetition',
            name='competition_store_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
